//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachPlan
    {
        public int PlanID { get; set; }
        public int CoachID { get; set; }
        public int SharedByUser { get; set; }
    
        public virtual User Coach { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual User SharingUser { get; set; }
    }
}
