//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using CoachUs.Data.Entities;
    
    public partial class CoachUsEntities : DbContext
    {
        public CoachUsEntities()
            : base("name=CoachUsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CoachUs.Data.Entities.Action> Actions { get; set; }
        public DbSet<Activity> Activities { get; set; }
        public DbSet<AthletePlan> AthletePlans { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventTraining> EventTrainings { get; set; }
        public DbSet<Fare> Fares { get; set; }
        public DbSet<File> Files { get; set; }
        public DbSet<Inventory> Inventories { get; set; }
        public DbSet<License> Licenses { get; set; }
        public DbSet<LicensePayment> LicensePayments { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<Plan> Plans { get; set; }
        public DbSet<ActivityResult> ActivityResults { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Sale> Sales { get; set; }
        public DbSet<Subscription> Subscriptions { get; set; }
        public DbSet<SubscriptionPayment> SubscriptionPayments { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<TeamPlan> TeamPlans { get; set; }
        public DbSet<TeamUser> TeamUsers { get; set; }
        public DbSet<Training> Trainings { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<ActivityCategory> ActivityCategories { get; set; }
    }
}
