//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public Plan()
        {
            this.Coachs = new HashSet<CoachPlan>();
            this.Teams = new HashSet<TeamPlan>();
            this.Trainings = new HashSet<Training>();
        }
    
        public int ID { get; set; }
        public int AuthorID { get; set; }
        public string Name { get; set; }
        public bool Template { get; set; }
        public Nullable<int> CoachID { get; set; }
        public Nullable<int> AthleteID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int LastModifierID { get; set; }
        public System.DateTime LastModifyDate { get; set; }
    
        public virtual ICollection<CoachPlan> Coachs { get; set; }
        public virtual User Athlete { get; set; }
        public virtual User Author { get; set; }
        public virtual User Coach { get; set; }
        public virtual User Modifier { get; set; }
        public virtual ICollection<TeamPlan> Teams { get; set; }
        public virtual ICollection<Training> Trainings { get; set; }
    }
}
