//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoachUs.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CoachPlans = new HashSet<CoachPlan>();
            this.SharedPlans = new HashSet<CoachPlan>();
            this.Licenses = new HashSet<License>();
            this.Plans = new HashSet<Plan>();
            this.AuthorPlans = new HashSet<Plan>();
            this.ModifierPlans = new HashSet<Plan>();
            this.BuyerPlans = new HashSet<Plan>();
            this.BuyerSales = new HashSet<Sale>();
            this.SellerSales = new HashSet<Sale>();
            this.Subscriptions = new HashSet<Subscription>();
            this.OwnTeams = new HashSet<Team>();
            this.SharedTeamPlans = new HashSet<TeamPlan>();
            this.Teams = new HashSet<TeamUser>();
        }
    
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public string Laterality { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
        public Nullable<int> PictureID { get; set; }
    
        public virtual ICollection<CoachPlan> CoachPlans { get; set; }
        public virtual ICollection<CoachPlan> SharedPlans { get; set; }
        public virtual File File { get; set; }
        public virtual ICollection<License> Licenses { get; set; }
        public virtual ICollection<Plan> Plans { get; set; }
        public virtual ICollection<Plan> AuthorPlans { get; set; }
        public virtual ICollection<Plan> ModifierPlans { get; set; }
        public virtual ICollection<Plan> BuyerPlans { get; set; }
        public virtual ICollection<Sale> BuyerSales { get; set; }
        public virtual ICollection<Sale> SellerSales { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<Team> OwnTeams { get; set; }
        public virtual ICollection<TeamPlan> SharedTeamPlans { get; set; }
        public virtual ICollection<TeamUser> Teams { get; set; }
    }
}
